### ISSUE TITLE
Improved documentation: Spark migration command

### ISSUE THREAD

**Issue by MBerbert** [blazor-spark/blazor-spark#1]
In the documentation, where it demonstrates how to perform the migration with the spark command, for those who do not have **'dotnet-ef'** installed, the command will not work.

![image](https://user-images.githubusercontent.com/10320004/229376245-7d30cdd0-7990-4044-89a5-22a5c2bccf1e.png)

It would be interesting to warn about this point. Maybe leave the link to 'https://learn.microsoft.com/en-us/ef/core/cli/dotnet' or put the command:

`dotnet tool install --global dotnet-ef`

I'm on a new pc, and I ended up facing this problem, even though I try to be familiar with ef-dotnet, it took me a while to understand what was missing 😂😂

By the way, excellent job!👏

**Comment by alerch37** [comment]
I second this!  So glad I checked out the documentation and found this post - I wasn't sure what I was missing.

**Comment by westonwalker** [comment]
Thank you for the feedback. I'll be adding this to the docs ASAP.

**Comment by westonwalker** [comment]
This has been added to the docs. You can see it here - https://blazorspark.com/docs/installation/
