### ISSUE TITLE
Install template wont work 

### ISSUE THREAD

**Issue by okelot** [blazor-spark/blazor-spark#13]
To replicate issue just run 'spark install' before manually installing the BlazorSpark template. It would gives an error but still shows that the installation was success. Spark wont work unless you manually install the template.

![image](https://github.com/blazor-spark/blazor-spark/assets/1550447/0ef516da-f9ff-4a7b-888f-c2eaceb22b6d)

The issue is that in InstallSparkCommand.cs line 16, '--' is missing from the install command.

**Comment by westonwalker** [comment]
What version of the .NET sdk do you have?

Spark only supports .NET 7. You can check with the "dotnet --list-sdks"

**Comment by okelot** [comment]
I see. I have latest version but it seems something was wrong from my side (I had to modify global.json). I will retract PR request and close the issue. 
![image](https://github.com/blazor-spark/blazor-spark/assets/1550447/7e126d2b-0516-4959-b61f-70cb7158ce42)
