### ISSUE TITLE
About section is blank

### ISSUE THREAD

**Issue by AndrewJesse** [blazor-spark/blazor-spark#15]
It would look really nice to have an About section, especially so it has a description when it's pinned on my profile home page:)

Here are a couple suggestions for the About section:
"Easily construct comprehensive Blazor Server applications using Blazor Spark, our versatile open-source framework."
"Quickly build a full-stack Blazor Server application with this open-source Blazor framework"

![image](https://github.com/blazor-spark/blazor-spark/assets/53543737/c16009f7-19cb-4ab0-ba6c-ad3f897a3d15)

**Comment by westonwalker** [comment]
Done! I didn't even know the about section existed. Thanks for pointing it out.
