### ISSUE TITLE
Few questions and suggestions

### ISSUE THREAD

**Issue by sturlath** [blazor-spark/blazor-spark#2]
I´m really interested in this project but would like to see few things

- Summary of the things you have been sharing on [Twitter  ](https://twitter.com/wes_walke)
  - the philosophy behind the the framework and what sparked it etc.
- High level roadmap for things to come and in what order you think they will be developed
- What flavour of Blazor is this WASM/Server and even if its super early do we know how this will play with Blazor United?
- Activate the Discussion tab for this repo for discussion like this 😅

I have downloaded and tested this since it is probably going to change a lot I´m not ready to go all in just yet 😆 but would love to have more information.

**Comment by westonwalker** [comment]
I agree, having answers to the questions you proposed would help bring more clarity to the project.

Do you think adding a changelog would be helpful as well?

**Comment by westonwalker** [comment]
Also, discussions have been enabled. Rather than answering the rest of your questions here, I'll work on providing answers in the docs.

**Comment by sturlath** [comment]
> Do you think adding a changelog would be helpful as well?

Yes some place to follow what has been worked on with some number would be great. Now could be 0.2 and then you work your way to 1.0 when you think you will not do some major changes 😉

At least my 5 cents

**Comment by westonwalker** [comment]
Added a roadmap to the documentation site on the introduction page. I'll start working on implementing a changelog soon!
![image](https://user-images.githubusercontent.com/66449990/233172511-e2ddb088-ae65-47c5-b6d4-4670b4b9914f.png)
